services:
  - type: web
    name: openai-chatbot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node api/chat.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: true
